# -*- coding: utf-8 -*-
"""reliabilityTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzGNt-pErdrgaHVud1SBgHVfdqFlywf2
"""

import os
import time

# Define the size of the data to be written and read
DATA_SIZE = 1024 * 1024 # 1MB

# Define the number of iterations for the test
ITERATIONS = 10

# Define the path to the Flash memory device
DEVICE_PATH = "/dev/sda1" # Replace with your actual device path

# Open the device for writing and reading
device = open(DEVICE_PATH, "wb+")

# Define a function to write and read data from the device
def perform_reliability_test():
    # Generate random data to be written
    data = os.urandom(DATA_SIZE)
    
    # Write the data to the device
    device.write(data)
    device.flush()
    
    # Read the data from the device
    device.seek(0)
    read_data = device.read(DATA_SIZE)
    
    # Verify that the data read matches the data written
    assert data == read_data, "Data read does not