# -*- coding: utf-8 -*-
"""speedTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTwJ9mNvy8oiXBcrBBG8XOqUV5fX5H1p
"""

import time
import random

# Define the size of the data to be written and read
DATA_SIZE = 1024 * 1024 # 1MB

# Define the number of iterations for the test
ITERATIONS = 10

# Define the path to the Flash memory device
DEVICE_PATH = "/dev/sda1" # Replace with your actual device path

# Open the device for writing and reading
device = open(DEVICE_PATH, "wb+")

# Define a function to write and read data from the device
def perform_speed_test():
    # Generate random data to be written
    data = bytearray(random.getrandbits(8) for _ in range(DATA_SIZE))
    
    # Write the data to the device
    start_time = time.time()
    device.write(data)
    device.flush()
    write_time = time.time() - start_time
    
    # Read the data from the device
    device.seek(0)
    start_time = time.time()
    read_data = device.read(DATA_SIZE)
    read_time = time.time() - start_time
    
    # Verify that the data read matches the data written
    assert data == read_data, "Data read does not match data written"
    
    # Return the write and read times
    return write_time, read_time

# Run the speed test for the specified number of iterations
write_times = []
read_times = []
for i in range(ITERATIONS):
    write_time, read_time = perform_speed_test()
    write_times.append(write_time)
    read_times.append(read_time)

# Compute the average write and read times
avg_write_time = sum(write_times) / len(write_times)
avg_read_time = sum(read_times) / len(read_times)

# Print the results
print("Average write time: %.2f seconds" % avg_write_time)
print("Average read time: %.2f seconds" % avg_read_time)

# Close the device
device.close()

